#jdbc properties

#spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
#spring.datasource.username=system
#spring.datasource.password=manager


#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql:///NTSPBMS616DB

#Activate the profile
spring: 
  profiles: 
    active: dev
    
---
spring:
  profiles: dev

  datasource: 
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql:///NTSPBMS616DB
      username: root
      password: root
      dbcp2: 
         max-total: 100
         initial-size: 10
         max-conn-lifetime-millis: 100000
      type: org.apache.commons.dbcp2.BasicDataSource
---
spring:
  profiles: test
 
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql:///NTSPBMS616DB
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    password: root
c3P0:
  maxSize: 100
  minSize: 10
  
---
spring:
  profiles: uat
  
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: system
    url: jdbc:oracle:thin:@localhost:1521:xe
    oracleucp:
      max-pool-size: 100
      time-to-live-connection-timeout: 100000
      min-pool-size: 10
    type: oracle.ucp.jdbc.PoolDataSourceImpl
    password: manager
    
---
spring: 
  profiles: prod
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari: 
      keepalive-time: 100000
      maximum-pool-size: 100
      minimum-idle: 10
    username: system
    url: jdbc:oracle:thin:@localhost:1521:xe
    password: manager
  


